name: "TQQQ Volatility Bot"
version: "1.0.1"
slug: "tqqq_bot"
description: "IBKR Sequential Allocation Matrix Bot"
arch:
  - aarch64
  - amd64
startup: application
options:
  ib_host: "ed1c039d-ibkr-gateway" # The internal hostname of the gateway addon
  ib_port: 4001
  reduction_factor: 0.95
schema:
  ib_host: str
  ib_port: int
  reduction_factor: float
depends_on:
  - ibkr_gateway
