# Inside tqqq_algo_trader/config.yaml

name: "TQQQ Algo Trader"
version: "1.0.16"
slug: "tqqq_algo_trader"
description: "Hass-tqqq-algo-trader-addon: Algorithmic Trader for TQQQ on Alpaca"
url: "https://github.com/Wakeboardsam/Hass-tqqq-algo-trader-addon.git"
arch:
  - aarch64
  - amd64
init: false
map:
  - config:rw

options:
  alpaca_api_key_id: ""
  alpaca_secret_key: ""
schema:
  alpaca_api_key_id: str
  alpaca_secret_key: str









